"""PRAgent 结构化研究工作流。"""

from .artifacts import DeepReadArtifactService, SavedDeepRead
from .compare import (
    COMPARISON_PROMPT_VERSION,
    ComparisonArtifactService,
    ComparisonBudget,
    ComparisonBudgetExceeded,
    ComparisonDraft,
    ComparisonError,
    ComparisonPrerequisiteError,
    ComparisonSchemaError,
    ComparisonWorkflow,
    SavedComparison,
    default_comparison_dimensions,
)
from .deep_read import (
    DEEP_READ_PROMPT_VERSION,
    DeepReadBudget,
    DeepReadBudgetExceeded,
    DeepReadDraft,
    DeepReadFieldDraft,
    DeepReadError,
    DeepReadSchemaError,
    DeepReadWorkflow,
)
from .schemas import (
    COMPARISON_SCHEMA_VERSION,
    DEEP_READ_FIELD_LABELS,
    DEEP_READ_FIELD_ORDER,
    DEEP_READ_SCHEMA_VERSION,
    ComparisonCell,
    ComparisonDimension,
    ComparisonDimensionCells,
    ComparisonMatrix,
    DeepReadCard,
    DeepReadField,
    EvidenceRef,
)

__all__ = [
    "COMPARISON_PROMPT_VERSION",
    "COMPARISON_SCHEMA_VERSION",
    "ComparisonArtifactService",
    "ComparisonBudget",
    "ComparisonBudgetExceeded",
    "ComparisonCell",
    "ComparisonDimension",
    "ComparisonDimensionCells",
    "ComparisonDraft",
    "ComparisonError",
    "ComparisonMatrix",
    "ComparisonPrerequisiteError",
    "ComparisonSchemaError",
    "ComparisonWorkflow",
    "DEEP_READ_FIELD_LABELS",
    "DEEP_READ_FIELD_ORDER",
    "DEEP_READ_PROMPT_VERSION",
    "DEEP_READ_SCHEMA_VERSION",
    "DeepReadArtifactService",
    "DeepReadBudget",
    "DeepReadBudgetExceeded",
    "DeepReadCard",
    "DeepReadDraft",
    "DeepReadError",
    "DeepReadField",
    "DeepReadFieldDraft",
    "DeepReadSchemaError",
    "DeepReadWorkflow",
    "EvidenceRef",
    "SavedComparison",
    "SavedDeepRead",
    "default_comparison_dimensions",
]
